# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndyMapsConverter
                                 A QGIS plugin
 This plugin imports/exports the QGIS project to the IndyMaps format (*.imx)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-03
        copyright            : (C) 2025 by Leonid Kolesnichenko
        email                : xperience439@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def pip_dependencies():
    import subprocess
    from configparser import ConfigParser
    from pathlib import Path
    from qgis.PyQt.QtCore import QStandardPaths

    metadata_txt = Path(__file__).parent / "metadata.txt"
    config = ConfigParser(allow_no_value=True)
    config.read(metadata_txt)
    metadata = dict(config["general"])
    deps = metadata.get('pip_dependencies', '')
    if not deps: return
    python = QStandardPaths.findExecutable("python")
    subprocess.run(
        f"{python} -m pip install --user {deps}",
        shell=True,
        check=True,
    )


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndyMapsConverter class from file IndyMapsConverter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indy_maps_converter import IndyMapsConverter

    return IndyMapsConverter(iface)
