# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndyMapsConverter
                                 A QGIS plugin
 This plugin imports/exports the QGIS project to the IndyMaps format (*.imx)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-03
        copyright            : (C) 2025 by Leonid Kolesnichenko
        email                : xperience439@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndyMapsConverter class from file IndyMapsConverter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indy_maps_converter import IndyMapsConverter
    return IndyMapsConverter(iface)
